# Generated by Django 3.1.7 on 2021-03-18 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20210318_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_date', models.DateField(verbose_name='Дата')),
                ('grade', models.SmallIntegerField(verbose_name='оценка')),
                ('grade_quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.quarters', verbose_name='четверть')),
                ('grade_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.subjects', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
